### Cretes a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Anshu02",
  "email": "anshu02@gmail.com",
  "address": "lukisarai, Bihar",
  "dateOfBirth": "1999-03-22",
  "registeredDate": "2026-05-11"

}
###