### Update an existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Iron Man Updated",
  "email": "absed@gmail.com",
  "address": "Begusarai, Bihar",
  "dateOfBirth": "2010-03-04"

}
###